
# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en
locales: [en, ca, es, oc]
# ignore_missing:

ignore_unused:
  - "decidim.authorization_handlers.members_picker_authorization_handler.*"
  - "decidim.verifications.members_picker_authorization.extra_explanation"
